on:
  workflow_dispatch: # can only be launched manually
name: Deploy New TD on ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon EC R
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Fill in the execution role ARN in the Amazon ECS task definition
        id: task-def-exec-arn
        uses: microsoft/variable-substitution@v1
        with:
          files: "task-definition.json"
        env:
          executionRoleArn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/folio-oimp-dev_oimp-poc_ecs_task_execution_role

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: folio/order-import-poc
          IMAGE_TAG: 'latest'
        with:
          task-definition: task-definition.json
          container-name: oimp-poc
          image: ${{ $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: oimp-poc
          cluster: tf-folio-oimp-dev-cluster
          wait-for-service-stability: true
          
